apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q02v7lxe0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q02v7lxe0-java-quarkus-gitops